name: Web Integration Tests

permissions:
  pull-requests: write

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ "9.x" ]
        browser: [ "chromium", "firefox", "webkit" ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Ensure browsers are installed
      run: pwsh tests/Web.IntegrationTests/bin/Debug/net9.0/playwright.ps1 install --with-deps ${{ matrix.browser }}  

    - name: Test
      run: dotnet test tests/Web.IntegrationTests --settings:tests/Web.IntegrationTests/${{ matrix.browser }}.runsettings --no-build --verbosity normal --logger trx --results-directory "TestResults/${{ matrix.dotnet-version }}/${{ matrix.browser }}"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: web-integration-test-results-${{ matrix.dotnet-version }}-${{ matrix.browser }}
        path: TestResults/${{ matrix.dotnet-version }}/${{ matrix.browser }}
      if: ${{ always() }}
